version: '2'
services:
  backendContainer:
    build:
      context: .
      args:
        FastAPIENV: "production"

    image: peak-end_backend

    container_name: backendContainer

    ports: 
    - "8080:8080"

    env_file:
    - .env

    environment:
    - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    - POSTGRE_NAME=${POSTGRE_NAME}
    - POSTGRE_PWD=${POSTGRE_PWD}

    volumes:
    - ./:/code