version: '2'
services:
  backendContainer:
    build:
      context: .
      args:
        FastAPIENV: "production"

    image: popopopony/peak-end_backend:v1

    container_name: backendContainer

    ports: 
    - "8080:8080"

    env_file:
    - .env

    environment:
    - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

    volumes:
    - ./:/code

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
    - 127.0.0.1:5432:5432

    expose:
      - 5432

    env_file:
      - .env

    environment:
      - POSTGRE_NAME=${POSTGRE_NAME}
      - POSTGRE_PWD=${POSTGRE_PWD}



  volumes:
    postgres_data: