export let song_lst = [{
    listened: 0,
    title: 'song1',
    artist: 'artist1',
    source: 'https://open.spotify.com/embed/track/4fZJyDjBtILM9PLqJSBYbJ?utm_source=generator',
    like: 0,
    splendid: 0,
    add: 0,
}, {
    listened: 0,
    title: 'song2',
    artist: 'artist2',
    source: 'https://open.spotify.com/embed/track/77zJUDrQyZxu9uDEP4WRiE?utm_source=generator',
    like: 0,
    splendid: 0,
    add: 0,
}, {
    listened: 0,
    title: 'song3',
    artist: 'artist3',
    source: 'https://open.spotify.com/embed/track/05dNly5n36DhY8tY0qLNBw?utm_source=generator',
    like: 0,
    splendid: 0,
    add: 0,
}]